name: Build
on: push

env:
  ANDROID_SDK_TOOLS:  "4333796"
  ANDROID_NDK:        "20.1.5948944"
  ANDROID_CMAKE:      "3.10.2.4988404"
  TARBALL_CACHE_KEY:  "tarballs-key-1"

jobs:
  debug:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        abi: [ x86, x86_64, armeabi-v7a, arm64-v8a ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache android-sdk.zip
        uses: actions/cache@v1
        with:
          key: android-sdk.zip-${{ env.ANDROID_SDK_TOOLS }}
          path: android-sdk

      - run: .github/installAndroidTools.sh

      - run: .github/installBuildDependencies.sh

      - name: Cache tarballs
        uses: actions/cache@v1
        with:
          key: ${{ env.TARBALL_CACHE_KEY }}
          path: dependency-builder/src/main/cpp/tarballs

      - run: ./dodownloadtarballs --serial

      - name: Build wvWare-Android
        run: ./gradlew assembleDebug -PdisablePreDex -Pabi=${{ matrix.abi }}

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache android-sdk.zip
        uses: actions/cache@v1
        with:
          key: android-sdk.zip-${{ env.ANDROID_SDK_TOOLS }}
          path: android-sdk

      - run: .github/installAndroidTools.sh

      - run: .github/installBuildDependencies.sh

      - name: Cache tarballs
        uses: actions/cache@v1
        with:
          key: ${{ env.TARBALL_CACHE_KEY }}
          path: dependency-builder/src/main/cpp/tarballs

      - run: ./dodownloadtarballs --serial

      - name: Build wvWare-Android
        run: ./gradlew assembleRelease -PdisablePreDex
